'use client'
import Card from "@/components/Card/Card"
import "./KeyMetrics.css"
import { BrainCircuit, Info, MoveDiagonal, TimerReset, Users } from "lucide-react"
import { formatTimeForAnalytics } from "@/utils/AnalyticsCalculator"
import { AiRecommendations } from "@/utils/AiRecommendations"
import { useModal } from "@/components/Modal/ModalContext"

export default function KeyMetrics() {
   const { showModal } = useModal();
   
   return (
      <section className="metrics-section">
         <h2>Key Metrics Overview</h2>
         <div className="metrics-grid">
            <div className="metric-card">
               <h3 className="text-s dfb align-center gap-6 justify-center text-center">Live Visitors <Users size={18} /></h3>
               <p>See how many users are on your site right now.</p><br />
               <Card padding="0 15px">
                  <div className="text-xs bold-600 pd-1 text-left">Live Visitors</div>
                  <div className="text-xxl bold-800 text-left">{250}</div>
                  <div 
                     className="text-xxs grey-5 dfb align-center gap-5 pd-2 visible-link fit"
                  ><Info size={18} /> Learn More</div>
               </Card>
            </div>
            <div className="metric-card">
               <h3 className="text-s dfb align-center gap-6 justify-center text-center">Average Session Duration <TimerReset size={18} /></h3>
               <p>Measure how long users are staying and engaging.</p><br />
               <Card padding="0 15px">
                  <div className="text-xs bold-600 pd-1 text-left">Average Session Duration</div>
                  <div className="text-xxl bold-800 text-left">{formatTimeForAnalytics(51)}</div>
                  <div 
                     className="text-xxs grey-5 dfb align-center gap-5 pd-2 visible-link fit"
                  ><Info size={18} /> Learn More</div>
               </Card>
            </div>
            <div className="metric-card">
               <h3 className="text-s dfb align-center gap-6 justify-center text-center">Bounce Rate <MoveDiagonal size={18} /></h3>
               <p>Track the percentage of users who leave without interacting.</p><br />
               <Card padding="0 15px">
                  <div className="text-xs bold-600 pd-1 text-left">Bounce Rate</div>
                  <div className="text-xxl bold-800 text-left">{21}%</div>
                  <div 
                     className="text-xxs grey-5 dfb align-center gap-5 pd-2 visible-link fit"
                  ><Info size={18} /> Learn More</div>
               </Card>
            </div>
            <div className="metric-card">
               <h3 className="text-s dfb align-center gap-6 justify-center text-center">AI Recommendations <BrainCircuit size={18} /></h3>
               <p>Actionable insights generated by AI to improve your site&apos;s performance.</p><br />
               <Card padding="15px">
                  <div className="text-xs bold-600 text-left">{AiRecommendations.bounceRate(21).title}</div>
                  <div className="text-xxs grey-5 pd-05 text-left">{AiRecommendations.bounceRate(21).text}</div>
                  <div className="text-xxs grey-5 pd-05 text-left">
                     <button 
                        className="xxxs"
                        onClick={() =>
                           showModal({
                              title: AiRecommendations.bounceRate(21).title,
                              content: (<>
                                 <div className="text-xxs">{AiRecommendations.bounceRate(21).text}</div><br />
                                 <div className="text-xxs bold-500">Apply the following to help:</div>
                                 <>{AiRecommendations.bounceRate(21).help.map((tip, index) => {
                                    return <div className="text-xxs" key={index}>- {tip}</div>
                                 })}</>
                              </>)
                           })
                        }
                     >{AiRecommendations.bounceRate(21).action}</button>
                  </div>
               </Card>
            </div>
         </div>
      </section>
   )
}
